global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "kafka"
    metrics_path: /metrics
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: "postgres"
    metrics_path: /metrics
    static_configs:
      - targets: ["postgres-exporter:9187"]
